logging:
  level:
    ROOT: INFO
server:
  port: 8888
spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/arturisimo/config-repo
info:
  app:
    name: Servidor de configuracion
    description: Servidor configuracion en NetFlix OSS
    version: 0.0.1-SNAPSHOT          